App:
  Name: 'Purwalenta - Staging'
  Version: '1.0'
  SignUpEmailAgent: 'user@purwalenta.com'

Database:
  Postgre:
    DSN: 'host=purwalenta_postgre port=5432 user=purwalenta dbname=purwalenta password=purwalenta sslmode=disable'
    MaxLifeTime: 10
    MaxIdle: 50
    MaxOpen: 100

  Redis:
    Address: 'purwalenta_redis:6379'
    Password: ''

UserAuthentication:
  SecretToken: 'cBBqT%,$WEF:f9mBW7qSvkuSnSO{7mLh*xuhofUm"E=#KdloyPlbWyj>^#551}A'
  MaxLifeTime: 86400000000

SMTP:
  Identity: 'Purwalenta User Management'
  Username: 'user@purwalenta.com'
  Password: '$c1[fO$mvqrc'
  Outgoing:
    Server: 'srv75.niagahoster.com'
    Port: 587
  Incoming:
    Server: 'srv75.niagahoster.com'
    Port: 143

Oauth2:
  Google:
    ClientID: '1073365596235-7u9g3f4aruilp6dukj1a8ltv02p0b3pm.apps.googleusercontent.com'
    ClientSecret: 'PA5lWBZyWM_dI9ok9pvOupS9'
    CallbackURL: 'https://purwalenta.com'
    Scopes:
      - 'https://www.googleapis.com/auth/userinfo.profile'
